# Generated by Django 2.1b1 on 2018-07-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_ver_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=128)),
            ],
        ),
    ]
