# Generated by Django 2.1b1 on 2018-07-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_ver_1', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
