# Generated by Django 2.1b1 on 2018-07-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-timestamp']},
        ),
    ]
